### ISSUE TITLE
Fake Call: Call Functionality

### ISSUE THREAD

**Issue by CarolinaZRM** [CarolinaZRM/CosmicComfort#22]
Fake Call Screen, the following should be displayed:
- Contact Name
- Contact Pic
--- Page look will depend on the dev's default OS choice, for now----

- Implement TIme Delay (amount of time that will pass between when the start call btn is pressed and when it actually triggers. This is decided by the user)

**Comment by JeremyCaban** [comment]
Done!

**Comment by JeremyCaban** [comment]
Done!
